name: TREM-Lite-Windows
on:
  push:
    branches: ["main"]

jobs:
  build-and-release:
    strategy:
      matrix:
        config:
          - os: windows-latest
            platform: win
            artifact_name: TREM-Lite-Windows
            artifact_path: |
              dist/*.exe
              dist/*.msi
        node-version: [18]

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:${{ matrix.config.platform }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_id }}
          release_name: Windows Build ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/TREM-Lite-Setup.exe
          asset_name: TREM-Lite-Setup.exe
          asset_content_type: application/octet-stream

      - name: Upload MSI Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/TREM-Lite.msi
          asset_name: TREM-Lite.msi
          asset_content_type: application/octet-stream
